using Content.Shared._AS.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._AS.NeoNote.UI;

/// <summary>
/// The ui for the view of list of notes.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NeoNoteUiFragmentList : Control
{
    public event Action? OnCreateButtonPressed;
    public event Action<int>? OnOpenButtonPressed;
    public event Action<int>? OnDeleteButtonPressed;

    public NeoNoteUiFragmentList()
    {
        RobustXamlLoader.Load(this);
        CreateButton.OnPressed += _ => OnCreateButtonPressed?.Invoke();
    }

    /// <summary>
    /// Populates the list view with notes.
    /// </summary>
    /// <param name="notes">The list of entries to display.</param>
    public void PopulateNotes(List<NeoNoteEntry> notes)
    {
        NotesContainer.RemoveAllChildren();

        if (notes.Count == 0)
        {
            NoNotesLabel.Visible = true;
            return;
        }

        NoNotesLabel.Visible = false;
        foreach (var note in notes)
        {
            var entry = new NeoNoteUiFragmentListEntry(note);
            entry.OnOpenButtonPressed += id => OnOpenButtonPressed?.Invoke(id);
            entry.OnDeleteButtonPressed += id => OnDeleteButtonPressed?.Invoke(id);
            NotesContainer.AddChild(entry);
        }
    }
}
