using Content.Shared._AS.CartridgeLoader.Cartridges;
using Content.Shared._AS.PersistentSystems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._AS.NeoNote.UI;

/// <summary>
/// Populate the ui with the contents of a note.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NeoNoteUiFragmentListEntry : Control
{
    public event Action<int>? OnOpenButtonPressed;
    public event Action<int>? OnDeleteButtonPressed;

    public NeoNoteUiFragmentListEntry(NeoNoteEntry note)
    {
        RobustXamlLoader.Load(this);

        TitleLabel.Text = note.Title != string.Empty ? note.Title : Loc.GetString("neonote-ui-title-placeholder");
        PreviewLabel.Text = note.Body;
        CreatedLabel.Text = Loc.GetString("neonote-ui-list-entry-created",
            ("time", CanonicalFormat.CanonDateTime(note.CreatedAt).ToString("yyyy-MM-dd HH:mm")));
        // If note has been edited show the last time it was edited.
        ModifiedLabel.Text = note.ModifiedAt is { } modified
            ? Loc.GetString("neonote-ui-list-entry-modified",
                ("time", CanonicalFormat.CanonDateTime(modified).ToString("yyyy-MM-dd HH:mm")))
            : string.Empty;

        OpenButton.OnPressed += _ => OnOpenButtonPressed?.Invoke(note.RecordId);
        DeleteButton.OnPressed += _ => OnDeleteButtonPressed?.Invoke(note.RecordId);
    }
}
