using Content.Shared._AS.CartridgeLoader.Cartridges;
using Content.Shared._AS.PersistentSystems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._AS.NeoNote.UI;

[GenerateTypedNameReferences]
public sealed partial class NeoNoteUiFragmentView : Control
{
    public event Action? OnClosePressed;
    public event Action<int>? OnEditPressed;
    public event Action<int>? OnDeletePressed;

    public NeoNoteUiFragmentView(NeoNoteEntry note)
    {
        RobustXamlLoader.Load(this);

        var recordId = note.RecordId;

        TitleLabel.Text = note.Title != string.Empty ? note.Title :  Loc.GetString("neonote-ui-title-placeholder");
        var msg = new FormattedMessage();
        msg.AddText(note.Body);
        BodyLabel.SetMessage(msg);

        CreatedLabel.Text = Loc.GetString("neonote-ui-list-entry-created",
            ("time", CanonicalFormat.CanonDateTime(note.CreatedAt).ToString("yyyy-MM-dd HH:mm")));

        ModifiedLabel.Text = note.ModifiedAt is { } modified
            ? Loc.GetString("neonote-ui-list-entry-modified",
                ("time", CanonicalFormat.CanonDateTime(modified).ToString("yyyy-MM-dd HH:mm")))
            : string.Empty;

        CloseButton.OnPressed += _ => OnClosePressed?.Invoke();
        EditButton.OnPressed += _ => OnEditPressed?.Invoke(recordId);
        DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke(recordId);
    }
}
