using Content.Shared._AS.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._AS.NeoNote.UI;

/// <summary>
/// The Edit view for NeoNote.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NeoNoteUiFragmentEdit : Control
{
    public event Action<SaveData>? OnSavePressed;
    public event Action? OnExitPressed;

    public NeoNoteUiFragmentEdit(NeoNoteEntry? note)
    {
        RobustXamlLoader.Load(this);

        var recordId = note?.RecordId;

        BodyEdit.Placeholder = new Rope.Leaf(Loc.GetString("neonote-ui-body-placeholder"));

        if (note is { } existing) // null recordId means this is a new note (create), otherwise it's an edit (save)
        {
            // Pre populate the fields of the note if they exist.
            TitleEdit.Text = existing.Title;
            BodyEdit.TextRope = new Rope.Leaf(existing.Body); // We use a rope because it's better for live editing text out of order.
            SaveButton.Text = Loc.GetString("neonote-ui-edit-save");
        }
        else
        {
            SaveButton.Text = Loc.GetString("neonote-ui-edit-create");
        }

        SaveButton.OnPressed += _ => OnSavePressed?.Invoke(new SaveData(recordId,
            TitleEdit.Text,
            Rope.Collapse(BodyEdit.TextRope))
            );

        ExitButton.OnPressed += _ => OnExitPressed?.Invoke();
    }

    // The note and its contents that was saved.
    public struct SaveData(int? recordId, string title, string body)
    {
        public readonly int? RecordId = recordId;
        public readonly string Title = title;
        public readonly string Body = body;
    }
}
