using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared.PDA;
using Robust.Client.UserInterface; // Aurora's Song
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Input; // Aurora's Song

namespace Content.Client.PDA.Ringer
{
    [GenerateTypedNameReferences]
    public sealed partial class RingtoneMenu : FancyWindow
    {
        public string[] PreviousNoteInputs = new[] { "A", "A", "A", "A", "A", "A" };
        public LineEdit[] RingerNoteInputs;

        public float RingerVolume => VolumeSlider.Value; // Aurora's Song

        public event Action? SetRingtoneButtonPressed;
        public event Action? TestRingtoneButtonPressed;

        public RingtoneMenu()
        {
            RobustXamlLoader.Load(this);

            SetRingerButton.OnPressed += _ => SetRingtoneButtonPressed?.Invoke();
            TestRingerButton.OnPressed += _ => TestRingtoneButtonPressed?.Invoke();
            VolumeSlider.OnValueChanged += OnVolumeSliderChanged; // Aurora's Song End -

            RingerNoteInputs = new[] { RingerNoteOneInput, RingerNoteTwoInput, RingerNoteThreeInput, RingerNoteFourInput, RingerNoteFiveInput, RingerNoteSixInput };

            for (var i = 0; i < RingerNoteInputs.Length; ++i)
            {
                var input = RingerNoteInputs[i];
                var index = i;

                input.OnTextChanged += args =>
                {
                    if (input.Text.Length <= 0)
                        return;

                    input.Text = args.Text.ToUpper();

                    var isValid = IsNote(input.Text);

                    if (!isValid)
                    {
                        input.Text = PreviousNoteInputs[index];
                        input.AddStyleClass("highlight");
                    }
                    else
                    {
                        PreviousNoteInputs[index] = input.Text;
                        input.RemoveStyleClass("highlight");
                    }

                    input.CursorPosition = input.Text.Length;
                };

                input.OnFocusExit += _ =>
                {
                    if (!IsNote(input.Text))
                    {
                        input.Text = PreviousNoteInputs[index];
                        input.RemoveStyleClass("highlight");
                    }
                };

                input.OnTextEntered += _ =>
                {
                    if (!IsNote(input.Text))
                    {
                        input.Text = PreviousNoteInputs[index];
                        input.RemoveStyleClass("highlight");
                    }
                    input.CursorPosition = input.Text.Length;
                };
            }
        }

        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            //Prevents the ringtone window from being resized
            return DragMode.Move;
        }

        /// <summary>
        /// Determines whether or not the characters inputed are authorized
        /// </summary>
        public static bool IsNote(string input)
        {
            if (input.Any(char.IsDigit))
                return false;

            input = input.Replace("#", "sharp");

            return Enum.TryParse(input, true, out Note _);
        }
        // Aurora's Song Start
        public void UpdateVolume(float volume)
        {
            VolumeLabel.Text = (volume+9).ToString("0.0"); // makes the volume 9 higher, such that -4dB (default) reads as a "5" on the 1-10 volume scale
            if(!VolumeSlider.Grabbed) //Is this actually possible to (not)occur? No clue, but I'm not planning on risking it
                VolumeSlider.SetValueWithoutEvent(volume);
        }

        private void OnVolumeSliderChanged(Robust.Client.UserInterface.Controls.Range range)
        {
            VolumeLabel.Text = (range.Value+9).ToString("0.0"); // makes the volume 9 higher, such that -4dB (default) reads as a "5" on the 1-10 volume scale
        }

        public void SetVolumeRange(float min, float max) // All of this stuff basically copied off of the Canister's systems, tbh
        {
            VolumeSlider.MinValue = min;
            VolumeSlider.MaxValue = max;
        }
        // Aurora's Song End
    }
}
